#
# Copyright (C) 2004 - 2018 AJA Video Systems, Inc.
# Proprietary and Confidential information.
# All righs reserved
#

.PHONY: all clean cleandeps
all:
	cd build && $(MAKE)

clean: cleandeps
	cd build && $(MAKE) $@

cleandeps:
	cd build && $(MAKE) $@
