# Top level Makefile for AJA Video API Classes under linux 2.6+
#
# Copyright (C) 2010 AJA Video Systems, Inc.  
# Proprietary and Confidential information.
#
# This file is the Linux analog of the ajaapi.sln file used with Windows.
# It's purpose is to build all the projects in the solution.
#

.PHONY: all clean cleandeps
all:
	cd build && $(MAKE)

clean: cleandeps
	cd build && $(MAKE) $@

cleandeps:
	cd build && $(MAKE) $@
