/* SPDX-License-Identifier: MIT */
/**
	@file		error.h
	@brief		Header file for NTV2V4L2Loopback demonstration class
	@copyright	(C) 2025 AJA Video Systems, Inc.  All rights reserved.
**/

#ifndef _ERROR_H
#define _ERROR_H

#define AJA_VW_SUCCESS 0
#define AJA_VW_INVALIDARGS 1
#define AJA_VW_INVALIDAJADEVICE 2
#define AJA_VW_AJADEVICENOTREADY 3
#define AJA_VW_AJADEVICENOCAPTURE 4
#define AJA_VW_INVALIDPIXELFORMAT 5
#define AJA_VW_AJADEVICENOPIXELFORMAT 6
#define AJA_VW_NOTSISUPPORT 7
#define AJA_VW_INVALIDINPUTCHANNEL 8
#define AJA_VW_INVALIDINPUTSOURCE 9
#define AJA_VW_ENABLECHANNELSFAILED 10
#define AJA_VW_ENABLEINPUTINTERRUPTFAILED 11
#define AJA_VW_SUBSCRIBEINPUTVERTICALEVENTFAILED 12
#define AJA_VW_SUBSCRIBEOUTPUTVERTICALEVENTFAILED 13
#define AJA_VW_SETSDITRANSITENABLEFAILED 14
#define AJA_VW_WAITFOROUTPUTVERTICALINTERRUPTFAILED 14
#define AJA_VW_INVALIDVIDEOFORMAT 15
#define AJA_VW_SETCAPTUREMODEFAILED 16
#define AJA_VW_SETFREERUNREFERENCEFAILED 17
#define AJA_VW_SETVIDEOFORMATFAILED 18
#define AJA_VW_SETVANCMODEOFFFAILED 19
#define AJA_VW_SETTSIFRAMEENABLEFAILED 20
#define AJA_VW_SET4KSQUARESENABLEFAILED 21
#define AJA_VW_SETFRAMEBUFFERFORMATFAILED 22
#define AJA_VW_INCORRECTMULTILINKAUDIOCHANNEL 23
#define AJA_VW_APPLYSIGNALROUTEFAILED 24
#define AJA_VW_ACINITFORINPUTFAILED 25
#define AJA_VW_ACSTARTFAILED 26
#define AJA_VW_ACSETVIDEOBUFFERFAILED 27
#define AJA_VW_ACSETAUDIOBUFFERFAILED 28
#define AJA_VW_ACSETANCBUFFERSFAILED 29
#define AJA_VW_V4L2DRIVEROPENFAILED 30
#define AJA_VW_V4L2DEVICECREATEFAILED 31
#define AJA_VW_V4L2DEVICEOPENFAILED 32
#define AJA_VW_ACTRANSFERFAILED 33
#define AJA_VW_ACGETINPUTTIMECODESFAILED 34
#define AJA_VW_ACSTOPFAILED 35
#define AJA_VW_V4L2DEVICEREMOVEFAILED 36
#define AJA_VW_ALSESETUPFAILED 37
#define AJA_VW_CONFIGAUDIOSYSTEMFAILED 38
#define AJA_VW_NOHDMISUPPORT 39
#define AJA_VW_GETFRAMESERVICESFAILED 40
#define AJA_VW_SETFRAMESERVICESFAILED 41
#define AJA_VW_GETDEVICEOWNERFAILED 42
#define AJA_VW_GETINPUTROUTEFAILED 43
#define AJA_VW_SETACFRAMERANGEFAILED 44
#define AJA_VW_MISSINGARGS 45
#define AJA_VW_GETPOINTERFAILED 46
#define AJA_VW_SAMPLEBUFFERSIZEMISMATCH 47

#endif // _ERROR_H
