/**
	@file		ntv2formatdescriptor.cpp
	@brief		Implementation of the NTV2FormatDescriptor class.
	@copyright	(C) 2016-2017 AJA Video Systems, Inc.	Proprietary and confidential information.
**/
#include "ntv2formatdescriptor.h"
#if defined(AJALinux)
	#include <string.h>  // For memset
	#include <stdint.h>
#endif
#include <sstream>
#include <iomanip>


using namespace std;

#if defined (NTV2_DEPRECATE)
	#define	AJA_LOCAL_STATIC	static
#else	//	!defined (NTV2_DEPRECATE)
	#define	AJA_LOCAL_STATIC
#endif	//	!defined (NTV2_DEPRECATE)

#define	AJA_FD_BEGIN			NTV2FormatDescriptor (
#define	AJA_FD_END				0)
#define	AJA_FD_NOTSUPPORTED		NTV2FormatDescriptor ()
#define	AJA_FD_TBD				NTV2FormatDescriptor ()


const AJA_LOCAL_STATIC NTV2FormatDescriptor	formatDescriptorTable [NTV2_NUM_STANDARDS] [NTV2_FBF_NUMFRAMEBUFFERFORMATS] =
{
	{/////	NTV2_STANDARD_1080											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_YCBCRLINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_YCBCRLINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080_DVCPRO,	HD_YCBCRLINEPITCH_1080_DVCPRO,			AJA_FD_END,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080_QREZ,	HD_NUMCOMPONENTPIXELS_1080_QREZ,	HD_YCBCRLINEPITCH_1080_QREZ,			AJA_FD_END,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080_HDV,		HD_YCBCRLINEPITCH_1080_HDV,				AJA_FD_END,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB24LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB24LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB48LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2,			AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_720											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_YCBCRLINEPITCH_720,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_YCBCRLINEPITCH_720,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720_DVCPRO,	HD_YCBCRLINEPITCH_720_DVCPRO,			AJA_FD_END,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720_QREZ,		HD_NUMCOMPONENTPIXELS_720_QREZ,		HD_YCBCRLINEPITCH_720_QREZ,				AJA_FD_END,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720_HDV,		HD_YCBCRLINEPITCH_720_HDV,				AJA_FD_END,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			RGB24LINEPITCH_720,						AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			RGB24LINEPITCH_720,						AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			RGB48LINEPITCH_720,						AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720*2,			AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_720,			HD_NUMCOMPONENTPIXELS_720,			HD_NUMCOMPONENTPIXELS_720/4,			AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_525											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					YCBCRLINEPITCH_SD,						AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2/4,					AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2/4,					AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					YCBCRLINEPITCH_SD,						AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					RGB24LINEPITCH_525,						AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					RGB24LINEPITCH_525,						AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					RGB48LINEPITCH_525,						AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*4/3,					AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2,					AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			NUMACTIVELINES_525,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS/4,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_625											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					YCBCRLINEPITCH_SD,						AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2/4,					AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2/4,					AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					YCBCRLINEPITCH_SD,						AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					RGB24LINEPITCH_625,						AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					RGB24LINEPITCH_625,						AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					RGB48LINEPITCH_625,						AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS,						AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*4/3,					AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS*2,					AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			NUMACTIVELINES_625,				NUMCOMPONENTPIXELS,					NUMCOMPONENTPIXELS/4,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_1080p											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_YCBCRLINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_YCBCRLINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080_DVCPRO,	HD_YCBCRLINEPITCH_1080_DVCPRO,			AJA_FD_END,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080_QREZ,	HD_NUMCOMPONENTPIXELS_1080_QREZ,	HD_YCBCRLINEPITCH_1080_QREZ,			AJA_FD_END,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080_HDV,		HD_YCBCRLINEPITCH_1080_HDV,				AJA_FD_END,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB24LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB24LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			RGB48LINEPITCH_1080,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080*2,			AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			((HD_NUMCOMPONENTPIXELS_1080*10)/8)/4,	AJA_FD_END,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			((HD_NUMCOMPONENTPIXELS_1080*10)/8)/4,	AJA_FD_END,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_1080,			HD_NUMCOMPONENTPIXELS_1080/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_2K											inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			RGB48LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2,				AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			((HD_NUMCOMPONENTPIXELS_2K*10)/8)/4,	AJA_FD_END,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			((HD_NUMCOMPONENTPIXELS_2K*10)/8)/4,	AJA_FD_END,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_2K,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_2Kx1080p										inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB48LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2,				AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_2Kx1080i										inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_YCBCRLINEPITCH_2K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB24LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			RGB48LINEPITCH_2048,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K*2,				AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMACTIVELINES_1080,			HD_NUMCOMPONENTPIXELS_2K,			HD_NUMCOMPONENTPIXELS_2K/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_3840x2160p									inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_YCBCRLINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2/4,		AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2/4,		AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_YCBCRLINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB24LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB24LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB48LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*4/3,		AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2,			AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_TBD,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_TBD,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD/4,			AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_4096x2160p									inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_YCBCRLINEPITCH_4K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_YCBCRLINEPITCH_4K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB24LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB24LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB48LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2,				AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_TBD,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_TBD,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_3840HFR										inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_YCBCRLINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2/4,		AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2/4,		AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_YCBCRLINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB24LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB24LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		RGB48LINEPITCH_3840,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD,			AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*4/3,		AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD*2,			AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_TBD,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_TBD,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_QUADHD,		HD_NUMCOMPONENTPIXELS_QUADHD/4,			AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	},
	{/////	NTV2_STANDARD_4096HFR										inNumLines						inNumPixels							inLinePitch								inFirstActiveLine
		/* NTV2_FBF_10BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_YCBCRLINEPITCH_4K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ARGB */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_RGBA */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_YUY2 */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2/4,			AJA_FD_END,
		/* NTV2_FBF_ABGR */						AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCR_DPX */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_YCBCRLINEPITCH_4K,					AJA_FD_END,
		/* NTV2_FBF_8BIT_DVCPRO */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_QREZ */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_HDV */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_24BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB24LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_24BIT_BGR */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB24LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_10BIT_YCBCRA */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_DPX_LITTLEENDIAN */	AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_48BIT_RGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			RGB48LINEPITCH_4096,					AJA_FD_END,
		/* NTV2_FBF_PRORES */					AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_DVCPRO */			AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_PRORES_HDV */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RGB_PACKED */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K,				AJA_FD_END,
		/* NTV2_FBF_10BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*4/3,			AJA_FD_END,
		/* NTV2_FBF_16BIT_ARGB */				AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K*2,				AJA_FD_END,
		/* NTV2_FBF_UNUSED_23 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_RAW_RGB */			AJA_FD_TBD,
		/* NTV2_FBF_10BIT_RAW_YCBCR */			AJA_FD_TBD,
		/* NTV2_FBF_UNUSED_26 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_UNUSED_27 */				AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_420PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_10BIT_YCBCR_422PL */		AJA_FD_NOTSUPPORTED,
		/* NTV2_FBF_8BIT_YCBCR_420PL */			AJA_FD_BEGIN			HD_NUMLINES_4K,					HD_NUMCOMPONENTPIXELS_4K,			HD_NUMCOMPONENTPIXELS_4K/4,				AJA_FD_END,
		/* NTV2_FBF_8BIT_YCBCR_422PL */			AJA_FD_NOTSUPPORTED
	}
};	//	formatDescriptorTable


NTV2FormatDescriptor::NTV2FormatDescriptor (const NTV2Standard			inStandard,
											const NTV2FrameBufferFormat	inFrameBufferFormat,
											const NTV2VANCMode			inVancMode)
{
	MakeInvalid ();
	if (!NTV2_IS_VALID_STANDARD (inStandard))
		return;	//	bad standard
	if (!NTV2_IS_VALID_FRAME_BUFFER_FORMAT (inFrameBufferFormat))
		return;	//	bad FBF
	if (!NTV2_IS_VALID_VANCMODE (inVancMode))
		return;	//	bad Vanc mode

	//	The 'formatDescriptorTable' handles everything but VANC...
	const NTV2FormatDescriptor	&	result			(formatDescriptorTable[inStandard][inFrameBufferFormat]);
	*this = result;

	mStandard		= inStandard;
	mPixelFormat	= inFrameBufferFormat;
	mVancMode		= inVancMode;

	//	Account for VANC...
	if (NTV2_IS_VANCMODE_ON (inVancMode))
	{
		const ULWord					numActiveLines	(numLines);
		switch (inStandard)
		{
			case NTV2_STANDARD_1080:
			case NTV2_STANDARD_1080p:	numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 1114 : 1112;	break;

			case NTV2_STANDARD_720:		numLines = 740;													break;

			case NTV2_STANDARD_525:		numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 514 : 508;		break;

			case NTV2_STANDARD_625:		numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 612 : 598;		break;

			case NTV2_STANDARD_2K:		numLines = 1588;												break;

			default:					MakeInvalid ();													return;
		}
		firstActiveLine = numLines - numActiveLines;
	}
	if (NTV2_IS_FBF_PLANAR (inFrameBufferFormat))
		FinalizePlanar();

}	//	construct from NTV2Standard & NTV2VANCMode


void NTV2FormatDescriptor::FinalizePlanar (void)
{
	NTV2_ASSERT (NTV2_IS_FBF_PLANAR (mPixelFormat));
	mNumPlanes = 2;		//	For now, all support planar formats have two planes
	switch (mPixelFormat)
	{
		case NTV2_FBF_10BIT_YCBCR_420PL:	mLinePitch[0] = 20;			mLinePitch[1] = 20;				break;
		case NTV2_FBF_10BIT_YCBCR_422PL:	mLinePitch[0] = 20;			mLinePitch[1] = 20;				break;
		case NTV2_FBF_8BIT_YCBCR_420PL:		mLinePitch[0] = numPixels;	mLinePitch[1] = numPixels / 2;	break;
		case NTV2_FBF_8BIT_YCBCR_422PL:		mLinePitch[0] = 20;			mLinePitch[1] = 20;				break;
		default:							MakeInvalid ();
	}
}

NTV2FormatDescriptor::NTV2FormatDescriptor (const NTV2VideoFormat		inVideoFormat,
											const NTV2FrameBufferFormat	inFrameBufferFormat,
											const NTV2VANCMode			inVancMode)
{
	MakeInvalid ();
	const NTV2Standard	inStandard	(::GetNTV2StandardFromVideoFormat (inVideoFormat));
	if (!NTV2_IS_VALID_STANDARD (inStandard))
		return;	//	bad standard
	if (!NTV2_IS_VALID_FRAME_BUFFER_FORMAT (inFrameBufferFormat))
		return;	//	bad FBF
	if (!NTV2_IS_VALID_VANCMODE (inVancMode))
		return;	//	bad Vanc mode

	*this = formatDescriptorTable[inStandard][inFrameBufferFormat];		//	The 'formatDescriptorTable' handles everything but VANC

	mVideoFormat	= inVideoFormat;
	mStandard		= inStandard;
	mPixelFormat	= inFrameBufferFormat;
	mVancMode		= inVancMode;
	m2Kby1080		= NTV2_IS_2K1080_STANDARD(mStandard);

	//	Account for VANC...
	if (NTV2_IS_VANCMODE_ON (inVancMode))
	{
		const ULWord					numActiveLines	(numLines);
		switch (inStandard)
		{
			case NTV2_STANDARD_1080:
			case NTV2_STANDARD_1080p:	numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 1114 : 1112;	break;

			case NTV2_STANDARD_720:		numLines = 740;													break;

			case NTV2_STANDARD_525:		numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 514 : 508;		break;

			case NTV2_STANDARD_625:		numLines = NTV2_IS_VANCMODE_TALLER(inVancMode) ? 612 : 598;		break;

			case NTV2_STANDARD_2K:		numLines = 1588;												break;

			default:					MakeInvalid ();													return;
		}
		firstActiveLine = numLines - numActiveLines;
	}
	if (NTV2_IS_FBF_PLANAR (inFrameBufferFormat))
		FinalizePlanar();

}	//	construct from NTV2VideoFormat & NTV2VANCMode


#if !defined (NTV2_DEPRECATE_13_0)
	NTV2FormatDescriptor::NTV2FormatDescriptor (const NTV2Standard			inVideoStandard,
												const NTV2FrameBufferFormat	inFrameBufferFormat,
												const bool					inVANCenabled,
												const bool					in2Kby1080,
												const bool					inWideVANC)
	{
		MakeInvalid ();
		if (!NTV2_IS_VALID_STANDARD (inVideoStandard))
			return;	//	bad standard
		if (!NTV2_IS_VALID_FRAME_BUFFER_FORMAT (inFrameBufferFormat))
			return;	//	bad FBF
		if (inWideVANC && !inVANCenabled)
			return;	//	conflicting VANC params
	
		//	The 'formatDescriptorTable' handles everything but VANC...
		const NTV2FormatDescriptor	&	result			(formatDescriptorTable[inVideoStandard][inFrameBufferFormat]);
		const ULWord					numActiveLines	(result.numLines);
		*this = result;

		switch(inVideoStandard)
		{
		case NTV2_STANDARD_1080:
		case NTV2_STANDARD_1080p:
			mFrameGeometry = NTV2_FG_1920x1080;
			if(inVANCenabled)
			{
				numLines = inWideVANC ? 1114 : 1112;
				mFrameGeometry = inWideVANC ? NTV2_FG_1920x1114 : NTV2_FG_1920x1112;
			}
			break;
		case NTV2_STANDARD_720:
			mFrameGeometry = NTV2_FG_1280x720;
			if(inVANCenabled)
			{
				numLines = 740;
				mFrameGeometry = NTV2_FG_1280x740;
			}
			break;
		case NTV2_STANDARD_525:
			mFrameGeometry = NTV2_FG_720x486;
			if(inVANCenabled)
			{
				numLines = inWideVANC ? 514 : 508;
				mFrameGeometry = inWideVANC ? NTV2_FG_720x514 : NTV2_FG_720x508;
			}
			break;
		case NTV2_STANDARD_625:
			mFrameGeometry = NTV2_FG_720x576;
			if(inVANCenabled)
			{
				numLines = inWideVANC ? 612 : 598;
				mFrameGeometry = inWideVANC ? NTV2_FG_720x612 : NTV2_FG_720x598;
			}
			break;
		case NTV2_STANDARD_2K:
			mFrameGeometry = NTV2_FG_2048x1556;
			if(inVANCenabled)
			{
				numLines = 1588;
				mFrameGeometry = NTV2_FG_2048x1588;
			}
			break;
		case NTV2_STANDARD_2Kx1080p:
		case NTV2_STANDARD_2Kx1080i:
			mFrameGeometry = NTV2_FG_2048x1080;
			if(inVANCenabled)
			{
				numLines = inWideVANC ? 1114 : 1112;
				mFrameGeometry = inWideVANC ? NTV2_FG_2048x1114 : NTV2_FG_2048x1112;
			}
			break;
		case NTV2_STANDARD_3840x2160p:
			case NTV2_STANDARD_3840HFR:
			mFrameGeometry = NTV2_FG_4x1920x1080;
			break;
		case NTV2_STANDARD_4096x2160p:
		case NTV2_STANDARD_4096HFR:
			mFrameGeometry = NTV2_FG_4x2048x1080;
			break;
		case NTV2_NUM_STANDARDS:
			break;
		}

		firstActiveLine = numLines - numActiveLines;
		mStandard		= inVideoStandard;
		mPixelFormat	= inFrameBufferFormat;
		m2Kby1080		= in2Kby1080;
		mVancMode		= NTV2VANCModeFromBools (inVANCenabled, inWideVANC);

		if (NTV2_IS_FBF_PLANAR (inFrameBufferFormat))
			FinalizePlanar();
	
	}	//	construct from NTV2Standard

	NTV2FormatDescriptor::NTV2FormatDescriptor (const NTV2VideoFormat		inVideoFormat,
												const NTV2FrameBufferFormat	inFrameBufferFormat,
												const bool					inVANCenabled,
												const bool					inWideVANC)
	{
		NTV2FormatDescriptor	result	(::GetNTV2StandardFromVideoFormat (inVideoFormat),
											inFrameBufferFormat,
											inVANCenabled,
											NTV2_IS_2K_1080_VIDEO_FORMAT (inVideoFormat) || NTV2_IS_4K_4096_VIDEO_FORMAT (inVideoFormat),
											inWideVANC);
		*this = result;
		mVideoFormat = inVideoFormat;
		mFrameGeometry = GetNTV2FrameGeometryFromVideoFormat(inVideoFormat);
	}	//	construct from NTV2VideoFormat

	NTV2FormatDescriptor GetFormatDescriptor (	const NTV2Standard			inVideoStandard,
												const NTV2FrameBufferFormat	inFrameBufferFormat,
												const bool					inVANCenabled,
												const bool					in2Kby1080,
												const bool					inWideVANC)
	{
		return NTV2FormatDescriptor (inVideoStandard, inFrameBufferFormat, inVANCenabled, in2Kby1080, inWideVANC);
	}


NTV2FormatDescriptor GetFormatDescriptor (	const NTV2VideoFormat		inVideoFormat,
											const NTV2FrameBufferFormat	inFrameBufferFormat,
											const bool					inVANCenabled,
											const bool					inWideVANC)
{
	return NTV2FormatDescriptor (inVideoFormat, inFrameBufferFormat, inVANCenabled, inWideVANC);
}
#endif	//	!defined (NTV2_DEPRECATE_13_0)


NTV2FormatDescriptor::NTV2FormatDescriptor ()
{
	MakeInvalid ();
}


NTV2FormatDescriptor::NTV2FormatDescriptor (const ULWord inNumLines, const ULWord inNumPixels, const ULWord inLinePitch, const ULWord inFirstActiveLine)
	:	numLines		(inNumLines),
		numPixels		(inNumPixels),
		linePitch		(inLinePitch),
		firstActiveLine	(inFirstActiveLine),
		mStandard		(NTV2_STANDARD_INVALID),
		mVideoFormat	(NTV2_FORMAT_UNKNOWN),
		mPixelFormat	(NTV2_FBF_INVALID),
		mVancMode		(NTV2_VANCMODE_INVALID),
		m2Kby1080		(false),
		mNumPlanes		(1),
		mFrameGeometry	(NTV2_FG_INVALID)
{
	mLinePitch[0] = inLinePitch * 4;	//	mLinePitch is in bytes, inLinePitch is in 32-bit longwords
	mLinePitch[1] = mLinePitch[2] = mLinePitch[3] = 0;
}


void NTV2FormatDescriptor::MakeInvalid (void)
{
	numLines		= 0;
	numPixels		= 0;
	linePitch		= 0;
	firstActiveLine	= 0;
	mStandard		= NTV2_STANDARD_INVALID;
	mVideoFormat	= NTV2_FORMAT_UNKNOWN;
	mPixelFormat	= NTV2_FBF_INVALID;
	mVancMode		= NTV2_VANCMODE_INVALID;
	m2Kby1080		= false;
	mLinePitch[0] = mLinePitch[1] = mLinePitch[2] = mLinePitch[3] = 0;
	mNumPlanes		= 0;
	mFrameGeometry	= NTV2_FG_INVALID;
}


bool NTV2FormatDescriptor::operator == (const NTV2FormatDescriptor & inRHS) const
{
	return numLines == inRHS.numLines  &&  numPixels == inRHS.numPixels
			&&  mNumPlanes == inRHS.mNumPlanes  &&  firstActiveLine == inRHS.firstActiveLine
			&&  mLinePitch[0] == inRHS.mLinePitch[0];
}


const void * NTV2FormatDescriptor::GetRowAddress (const void * pInStartAddress, const ULWord inRowIndex0, const UWord inPlaneIndex0) const
{
	if (inRowIndex0 >= numLines)
		return NULL;
	if (inPlaneIndex0 >= mNumPlanes)
		return NULL;

	const UByte *	pStart ((const UByte *) pInStartAddress);
	if (inPlaneIndex0 > 0)
		pStart += GetTotalRasterBytes(0);
	if (inPlaneIndex0 > 1)
		pStart += GetTotalRasterBytes(1);
	if (inPlaneIndex0 > 2)
		pStart += GetTotalRasterBytes(2);
	return pStart + inRowIndex0 * GetBytesPerRow (inPlaneIndex0);
}


bool NTV2FormatDescriptor::GetFirstChangedRow (const void * pInStartAddress1, const void * pInStartAddress2, ULWord & outFirstChangedRowNum) const
{
	outFirstChangedRowNum = 0xFFFFFFFF;
	if (!pInStartAddress1)
		return false;	//	NULL start address 1
	if (!pInStartAddress2)
		return false;	//	NULL start address 2
	if (pInStartAddress1 == pInStartAddress2)
		return false;	//	same start addresses
	if (!IsValid ())
		return false;	//	invalid

//	TODO:	COMPARE OTHER PLANES
	for (outFirstChangedRowNum = 0;  outFirstChangedRowNum < GetFullRasterHeight ();  outFirstChangedRowNum++)
		if (::memcmp (GetRowAddress ((UByte *) pInStartAddress1, outFirstChangedRowNum), GetRowAddress (pInStartAddress2, outFirstChangedRowNum), GetBytesPerRow ()))
			return true;	//	Success
	outFirstChangedRowNum = 0xFFFFFFFF;	//	No changes
	return true;	//	Success
}


bool NTV2FormatDescriptor::GetChangedLines (NTV2RasterLineOffsets & outDiffs, const void * pInBuffer1, const void * pInBuffer2, const ULWord inMaxLines) const
{
	outDiffs.clear ();
	if (!IsValid ())
		return false;	//	Invalid format descriptor
	if (!pInBuffer1 || !pInBuffer2)
		return false;	//	NULL or empty buffers

	const UByte *	pStartAddress1	(reinterpret_cast <const UByte *> (pInBuffer1));
	const UByte *	pStartAddress2	(reinterpret_cast <const UByte *> (pInBuffer2));

	if (GetRowAddress (pStartAddress1, GetFullRasterHeight() - 1) == NULL)
		return false;	//	buffer too small to fetch given rowOffset
	if (pInBuffer1 == pInBuffer2)
		return true;	//	Same buffer -- no diffs (success!)
	ULWord	maxLines	(inMaxLines ? inMaxLines : GetFullRasterHeight ());
	if (maxLines > GetFullRasterHeight())
		maxLines = GetFullRasterHeight();
//	TODO:	FIX PLANAR
	for (ULWord rowOffset (0);  rowOffset < maxLines;  rowOffset++)
		if (::memcmp (GetRowAddress (pStartAddress1, rowOffset), GetRowAddress (pStartAddress2, rowOffset), GetBytesPerRow ()))
			outDiffs.push_back (rowOffset);
	return true;
}


ostream & NTV2FormatDescriptor::Print (ostream & inOutStream, const bool inDetailed) const
{
	UWord	plane	(0);
	if (!IsValid ())
		inOutStream << "INVALID: ";
	inOutStream	<< GetFullRasterHeight() << " lines, "
				<< GetRasterWidth() << " pixels/line, ";
	if (IsPlanar())
		inOutStream << GetNumPlanes() << " plane(s)";
	do
	{
		if (IsPlanar())
			inOutStream << ", PL" << plane << ": ";
		inOutStream << GetBytesPerRow(plane) << " bytes/line";
	} while (++plane < GetNumPlanes());
	inOutStream << ", 1stAct=" << firstActiveLine;
	if (inDetailed)
	{
		inOutStream	<< " (";
		if (NTV2_IS_VALID_VIDEO_FORMAT (mVideoFormat))
			inOutStream << "'" << ::NTV2VideoFormatToString (mVideoFormat) << "'";
		else
			inOutStream << ::NTV2StandardToString (mStandard, true) << (m2Kby1080 ? " 2K" : "");
		if (mVancMode != NTV2_VANCMODE_OFF && mVancMode < NTV2_VANCMODE_INVALID)
			inOutStream << (mVancMode == NTV2_VANCMODE_TALLER ? " TallerVANC" : " TallVANC");
		if (NTV2_IS_VALID_FRAME_BUFFER_FORMAT (mPixelFormat))
			inOutStream << " '" << ::NTV2FrameBufferFormatToString (mPixelFormat, true) << "'";
		inOutStream << ")";
	}
	return inOutStream;
}


//	NTV2_VANCMODE_OFF							1080i	720p	525i	625i	1080p	2K		2K1080p		2K1080i		3840x2160p	4096x2160p	3840HFR		4096HFR
static const ULWord	LineNumbersF1 []	=	{	21,		26,		21,		23,		42,		211,	42,			21,			42,			42,			42,			42,			0	};
static const ULWord	LineNumbersF2 []	=	{	584,	27,		283,	336,	43,		1201,	43,			584,		0,			0,			0,			0,			0	};
//	NTV2_VANCMODE_TALL
static const ULWord	LineNumbersF1t []	=	{	5,		6,		10,		12,		10,		211,	10,			5,			10,			10,			10,			10,			0	};
static const ULWord	LineNumbersF2t []	=	{	568,	7,		272,	325,	11,		1201,	11,			568,		0,			0,			0,			0,			0	};
//	NTV2_VANCMODE_TALLER
static const ULWord	LineNumbersF1tt []	=	{	4,		6,		7,		5,		8,		211,	8,			4,			8,			8,			8,			8,			0	};
static const ULWord	LineNumbersF2tt []	=	{	567,	7,		269,	318,	9,		1201,	9,			567,		0,			0,			0,			0,			0	};


bool NTV2FormatDescriptor::GetSMPTELineNumber (const ULWord inLineOffset, ULWord & outSMPTELine, bool & outIsField2) const
{
	outIsField2 = false;
	outSMPTELine = 0;
	if (!IsValid())
		return false;
	if (!NTV2_IS_VALID_STANDARD(mStandard))
		return false;
	if (!NTV2_IS_VALID_VANCMODE (mVancMode))
		return false;

	const bool		is525i		(mStandard == NTV2_STANDARD_525);
	if (!NTV2_IS_PROGRESSIVE_STANDARD (mStandard))
		outIsField2 = (inLineOffset & 1)  ?  !is525i  :  is525i;

	const ULWord	divisor		(NTV2_IS_PROGRESSIVE_STANDARD(mStandard)  ?  1  :  2);
	ULWord			smpteLine	(0);

	switch (mVancMode)
	{
		case NTV2_VANCMODE_OFF:		smpteLine =  outIsField2  ?  LineNumbersF2[mStandard]   :  LineNumbersF1[mStandard];	break;
		case NTV2_VANCMODE_TALL:	smpteLine =  outIsField2  ?  LineNumbersF2t[mStandard]  :  LineNumbersF1t[mStandard];	break;
		case NTV2_VANCMODE_TALLER:	smpteLine =  outIsField2  ?  LineNumbersF2tt[mStandard] :  LineNumbersF1tt[mStandard];	break;
		default:					break;
	}
	outSMPTELine = inLineOffset/divisor + smpteLine;
	return true;
}


ostream & NTV2FormatDescriptor::PrintSMPTELineNumber (ostream & inOutStream, const ULWord inLineOffset) const
{
	ULWord	smpteLine	(0);
	bool	isF2		(false);
	if (GetSMPTELineNumber (inLineOffset, smpteLine, isF2))
	{
		if (!NTV2_IS_PROGRESSIVE_STANDARD (mStandard))
			inOutStream << "F" << (isF2 ? "2" : "1") << " ";
		inOutStream << "L" << dec << smpteLine;	//	(inLineOffset/divisor + smpteLine);
	}
	return inOutStream;
}


//	WHY IS NTV2SmpteLineNumber's CONSTRUCTOR HERE?
//	TO USE THE SAME LineNumbersF1/LineNumbersF2 TABLES (above)

NTV2SmpteLineNumber::NTV2SmpteLineNumber (const NTV2Standard inStandard)
{
	NTV2_ASSERT (inStandard < sizeof(LineNumbersF1) / sizeof(ULWord));
	*this = NTV2SmpteLineNumber (LineNumbersF1[inStandard],  LineNumbersF2[inStandard],  inStandard != NTV2_STANDARD_525,  inStandard);
}
