function(aja_cmake_install_misc)
	# CMake modules directory
	if (AJA_NTV2_INSTALL_CMAKE)
		install(FILES cmake/AJAVersionConfig.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJACommonPaths.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJACommonFlags.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJAQtHelpers.cmake				DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJABuildOptions.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJACMakeOptions.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJACommonDefines.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/linux_ldd_qt_libs.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/AJAHelpers.cmake				DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
		install(FILES cmake/bundle/linux/lin-ver.json.in	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux)
		install(FILES cmake/bundle/linux/desktop/aja_ntv2_documentation.desktop.in	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux/desktop)
		install(FILES cmake/bundle/linux/desktop/aja-controlpanel-ajadaemon.desktop.in	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux/desktop)
		install(FILES cmake/bundle/linux/desktop/aja-systemtest.desktop.in				DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux/desktop)
		install(FILES cmake/bundle/linux/desktop/aja-controlroom.desktop.in				DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux/desktop)
		install(FILES cmake/bundle/linux/desktop/aja-controlpanel.desktop.in			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/linux/desktop)
		install(FILES cmake/bundle/mac/Info.plist.in				DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/mac)
		install(FILES "cmake/bundle/mac/AJA NTV2 Documentation.webloc.in"	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/mac)
		install(FILES cmake/bundle/windows/win-ver-dll.rc.in		DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/windows)
		install(FILES cmake/bundle/windows/win-ver.rc.in			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/windows)
		install(FILES cmake/bundle/windows/aja_ntv2_documentation.url.in	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/bundle/windows)
		install(FILES cmake/toolchain/aja-ci-toolchain.cmake		DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/toolchain)
		install(FILES cmake/toolchain/msvc_toolchain.cmake			DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/toolchain)
		install(FILES cmake/toolchain/clang-unix_toolchain.cmake	DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/toolchain)
		install(FILES cmake/toolchain/clang-win_toolchain.cmake		DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/toolchain)
		install(FILES CMakeLists.txt								DESTINATION ${CMAKE_INSTALL_PREFIX}/)
		install(FILES cmake/opensource/ajaapps/CMakeLists.txt.in DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/opensource/ajaapps)
		install(FILES cmake/opensource/ajadriver/CMakeLists.txt.in DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/opensource/ajadriver)
		install(FILES cmake/opensource/ajalibraries/CMakeLists.txt.in DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/opensource/ajalibraries)
		if (AJA_NTV2_BUILD_OPENSOURCE)
			# Replace existing ajaapps/ajadriver/ajalibraries CMakeLists.txt with open-source versions.
			install(FILES cmake/opensource/ajaapps/CMakeLists.txt.in
					DESTINATION ${CMAKE_INSTALL_PREFIX}/ajaapps
					RENAME CMakeLists.txt)
			install(FILES cmake/opensource/ajadriver/CMakeLists.txt.in
					DESTINATION ${CMAKE_INSTALL_PREFIX}/ajadriver
					RENAME CMakeLists.txt)
			install(FILES cmake/opensource/ajalibraries/CMakeLists.txt.in
					DESTINATION ${CMAKE_INSTALL_PREFIX}/ajalibraries
					RENAME CMakeLists.txt)
		else()
			install(FILES ajaapps/CMakeLists.txt
				DESTINATION ${CMAKE_INSTALL_PREFIX}/ajaapps)
			install(FILES ajadriver/CMakeLists.txt
				DESTINATION ${CMAKE_INSTALL_PREFIX}/ajadriver)
			install(FILES ajalibraries/CMakeLists.txt
				DESTINATION ${CMAKE_INSTALL_PREFIX}/ajalibraries)
		endif()
	endif()
	if (AJANTV2_INSTALL_MISC)
		install(FILES Makefile DESTINATION ${CMAKE_INSTALL_PREFIX}/)
		# Legacy QMake build files
		file(WRITE build/local_config.pri "A_CONFIG=${CMAKE_BUILD_TYPE}")
		install(FILES build/config.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/_hevctools.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/libs.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/local_config.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/_ntv2demos.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/subdirs.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build)
		install(FILES build/ajacc/ajacc.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ajacc)
		install(FILES build/ajacc/ajacc.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ajacc)
		install(FILES build/ajantv2/ajantv2.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ajantv2)
		install(FILES build/ajantv2/ajantv2.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ajantv2)
		install(FILES build/ntv2demos/_democommonhevc.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos)
		install(FILES build/ntv2demos/_democommon.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos)
		install(FILES build/ntv2demos/burn/burn.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/burn)
		install(FILES build/ntv2demos/burn/burn.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/burn)
		install(FILES build/ntv2demos/burn4kquadrant/burn4kquadrant.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/burn4kquadrant)
		install(FILES build/ntv2demos/burn4kquadrant/burn4kquadrant.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/burn4kquadrant)
		install(FILES build/ntv2demos/capture/capture.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture)
		install(FILES build/ntv2demos/capture/capture.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture)
		install(FILES build/ntv2demos/capture4k/capture4k.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture4k)
		install(FILES build/ntv2demos/capture4k/capture4k.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture4k)
		install(FILES build/ntv2demos/capture8k/capture8k.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture8k)
		install(FILES build/ntv2demos/capture8k/capture8k.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/capture8k)
		install(FILES build/ntv2demos/ccgrabber/ccgrabber.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ccgrabber)
		install(FILES build/ntv2demos/ccgrabber/ccgrabber.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ccgrabber)
		install(FILES build/ntv2demos/ccplayer/ccplayer.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ccplayer)
		install(FILES build/ntv2demos/ccplayer/ccplayer.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ccplayer)
		install(FILES build/ntv2demos/dolbyplayer/dolbyplayer.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/dolbyplayer)
		install(FILES build/ntv2demos/dolbyplayer/dolbyplayer.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/dolbyplayer)
		install(FILES build/ntv2demos/enumerateboards/enumerateboards.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/enumerateboards)
		install(FILES build/ntv2demos/enumerateboards/enumerateboards.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/enumerateboards)
		install(FILES build/ntv2demos/fieldburn/fieldburn.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/fieldburn)
		install(FILES build/ntv2demos/fieldburn/fieldburn.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/fieldburn)
		install(FILES build/ntv2demos/hdrsetup/hdrsetup.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/hdrsetup)
		install(FILES build/ntv2demos/hdrsetup/hdrsetup.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/hdrsetup)
		install(FILES build/ntv2demos/konaipj2ksetup/konaipj2ksetup.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/konaipj2ksetup)
		install(FILES build/ntv2demos/konaipj2ksetup/konaipj2ksetup.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/konaipj2ksetup)
		install(FILES build/ntv2demos/konaipjsonsetup/konaipjsonsetup.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/konaipjsonsetup)
		install(FILES build/ntv2demos/konaipjsonsetup/konaipjsonsetup.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/konaipjsonsetup)
		install(FILES build/ntv2demos/llburn/llburn.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/llburn)
		install(FILES build/ntv2demos/llburn/llburn.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/llburn)
		install(FILES build/ntv2demos/ntv2encodehevc/ntv2encodehevc.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevc)
		install(FILES build/ntv2demos/ntv2encodehevc/ntv2encodehevc.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevc)
		install(FILES build/ntv2demos/ntv2encodehevcfile/ntv2encodehevcfile.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevcfile)
		install(FILES build/ntv2demos/ntv2encodehevcfile/ntv2encodehevcfile.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevcfile)
		install(FILES build/ntv2demos/ntv2encodehevcvif/ntv2encodehevcvif.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevcvif)
		install(FILES build/ntv2demos/ntv2encodehevcvif/ntv2encodehevcvif.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/ntv2encodehevcvif)
		install(FILES build/ntv2demos/outputtestpattern/outputtestpattern.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/outputtestpattern)
		install(FILES build/ntv2demos/outputtestpattern/outputtestpattern.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/outputtestpattern)
		install(FILES build/ntv2demos/player/player.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player)
		install(FILES build/ntv2demos/player/player.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player)
		install(FILES build/ntv2demos/player4k/player4k.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player4k)
		install(FILES build/ntv2demos/player4k/player4k.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player4k)
		install(FILES build/ntv2demos/player8k/player8k.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player8k)
		install(FILES build/ntv2demos/player8k/player8k.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/player8k)
		install(FILES build/ntv2demos/qtmultiinput/qtmultiinput.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/qtmultiinput)
		install(FILES build/ntv2demos/qtmultiinput/qtmultiinput.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/qtmultiinput)
		install(FILES build/ntv2demos/qtpreview/qtpreview.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/qtpreview)
		install(FILES build/ntv2demos/qtpreview/qtpreview.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/qtpreview)
		install(FILES build/ntv2demos/switchbitfile/switchbitfile.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/switchbitfile)
		install(FILES build/ntv2demos/switchbitfile/switchbitfile.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2demos/switchbitfile)
		install(FILES build/ntv2tools/hevcmaintenance/hevcmaintenance.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2tools/hevcmaintenance)
		install(FILES build/ntv2tools/hevcmaintenance/hevcmaintenance.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2tools/hevcmaintenance)
		install(FILES build/ntv2tools/qthevcmon/qthevcmon.pri DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2tools/qthevcmon)
		install(FILES build/ntv2tools/qthevcmon/qthevcmon.pro DESTINATION ${CMAKE_INSTALL_PREFIX}/build/ntv2tools/qthevcmon)
	endif()
endfunction(aja_cmake_install_misc)
