include_guard(GLOBAL)

# Platform-specific preprocessor defines
if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    list(APPEND AJANTV2_TARGET_COMPILE_DEFS
        -DAJA_WINDOWS
        -DMSWindows)

    list(APPEND AJANTV2_TARGET_COMPILE_DEFS_PRIVATE
        -D_WINDOWS
        -D_CONSOLE
        -DWIN32_LEAN_AND_MEAN
        -D_CRT_SECURE_NO_WARNINGS
        -D_SCL_SECURE_NO_WARNINGS)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND AJANTV2_TARGET_COMPILE_DEFS
        -DAJALinux
        -DAJA_LINUX)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    list(APPEND AJANTV2_TARGET_COMPILE_DEFS
        -DAJAMac
        -DAJA_MAC)
    list(APPEND AJANTV2_TARGET_COMPILE_DEFS_PRIVATE
        -D__STDC_CONSTANT_MACROS)
elseif (CMAKE_SYSTEM_NAME STREQUAL "BareMetal")
    list(APPEND AJANTV2_TARGET_COMPILE_DEFS
      -DNTV2_USE_STDINT
      -DAJABareMetal
      -DAJA_BAREMETAL)
endif()
