function (aja_get_msvc_tools_version)
	if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
		if (CMAKE_MAJOR_VERSION GREATER_EQUAL 3 AND CMAKE_MINOR_VERSION GREATER_EQUAL 12)
				# available in CMake 3.12 or later
				set(AJA_MSVC_TOOLSET_VERSION ${MSVC_TOOLSET_VERSION} PARENT_SCOPE)
			else()
			if (MSVC_VERSION EQUAL 1700)
				# Visual Studio 2012 (VS 11.0 v110 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 110 PARENT_SCOPE)
			elseif(MSVC_VERSION EQUAL 1800)
				# Visual Studio 2013 (VS 12.0 v120 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 120 PARENT_SCOPE)
			elseif(MSVC_VERSION EQUAL 1900)
				# Visual Studio 2015 (VS 14.0 v140 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 140 PARENT_SCOPE)
			elseif(MSVC_VERSION GREATER_EQUAL 1910 AND MSVC_VERSION LESS_EQUAL 1919)
				# VS 2017 (VS 14.1 v141 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 141 PARENT_SCOPE)
			elseif(MSVC_VERSION GREATER_EQUAL 1920 AND MSVC_VERSION LESS_EQUAL 1929)
				# VS 2019 (VS 16.0 v142 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 142 PARENT_SCOPE)
			elseif(MSVC_VERSION GREATER_EQUAL 1930 AND MSVC_VERSION LESS_EQUAL 1939)
				# VS 2022 (VS 17.0 v143 toolset)
				set(AJA_MSVC_TOOLSET_VERSION 143 PARENT_SCOPE)
			endif()
		endif()
	endif()
endfunction(aja_get_msvc_tools_version)

function(aja_set_msvc_runtime_library target linkage)
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
        aja_get_msvc_tools_version()
        if (CMAKE_BUILD_TYPE MATCHES "^(Debug|RelWithDebInfo)$")
            if (${linkage} STREQUAL "STATIC")
                message(STATUS "${target} (MD: Multi-Threaded Debug)")
                set_property(TARGET ${target} PROPERTY
                    MSVC_RUNTIME_LIBRARY "MultiThreadedDebug")
                set_target_properties(${target} PROPERTIES OUTPUT_NAME "${target}d_vs${AJA_MSVC_TOOLSET_VERSION}_MD")
            elseif(${linkage} STREQUAL "SHARED")
                message(STATUS "${target} (MDd: Multi-Threaded Debug DLL)")
                set_property(TARGET ${target} PROPERTY
                    MSVC_RUNTIME_LIBRARY "MultiThreadedDebugDLL")
                set_target_properties(${target} PROPERTIES OUTPUT_NAME "${target}${AJA_NTV2_SDK_VERSION_MAJOR}d_vs${AJA_MSVC_TOOLSET_VERSION}_MDd")
            endif()
        else()
            if (${linkage} STREQUAL "STATIC")
                message(STATUS "${target} (MT: Multi-Threaded)")
                set_property(TARGET ${target} PROPERTY
                    MSVC_RUNTIME_LIBRARY "MultiThreaded")
                set_target_properties(${target} PROPERTIES OUTPUT_NAME "${target}_vs${AJA_MSVC_TOOLSET_VERSION}_MT")
            elseif(${linkage} STREQUAL "SHARED")
                message(STATUS "${target} (MTd: Multi-Threaded DLL)")
                set_property(TARGET ${target} PROPERTY
                    MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
                set_target_properties(${target} PROPERTIES OUTPUT_NAME "${target}${AJA_NTV2_SDK_VERSION_MAJOR}_vs${AJA_MSVC_TOOLSET_VERSION}_MTd")
            endif()
        endif()
    endif()
endfunction(aja_set_msvc_runtime_library)
